services:
  app:
    image: msservergpstcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${TCP_PORT}:${TCP_PORT}"
    environment:
      - PORT=${PORT}
      - TCP_PORT=${TCP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_KEY_PREFIX=${REDIS_KEY_PREFIX}
    networks:
      - postgresql_postgres_network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  postgresql_postgres_network:
    external: true
