services:
  app:
    image: msservergpstcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${TCP_PORT}:${TCP_PORT}"
    environment:
      - PORT=${PORT}
      - TCP_PORT=${TCP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - tcp_network
    restart: unless-stopped

networks:
  tcp_network:
    driver: bridge 
