services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
      - "${TCP_PORT}:${TCP_PORT}"
    environment:
      - PORT=${PORT}
      - TCP_PORT=${TCP_PORT}
      - DATABASE_URL=postgresql://postgres:postgres@172.16.5.199:5432/msservergpstcp?schema=public
      - REDIS_HOST=172.16.5.199
      - REDIS_PORT=6379
    networks:
      - postgres_network
    restart: unless-stopped

networks:
  postgres_network: